version: "3"
name: tdisk

services:
  postgresql:
    container_name: 'postgresql'
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}

    image: postgres:13.14-alpine3.19
  
  redis-cache:
    container_name: 'redis-cache'
    ports:
      - "${REDIS_PORT}:6379"
    
    image: redis:alpine3.19
    
  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z-cpuv1
    command: server /data --console-address ":${MINIO_ADMIN_PORT}"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SIGNATURE=AWSv4
    volumes:
      - tdisk_minio_data:/data
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_ADMIN_PORT}:9001


volumes:
  tdisk_minio_data:
  rabbitmq-data:
  