"""Add key in StorageModel

Revision ID: 6eca5e33adc1
Revises: c100e49e9a9d
Create Date: 2024-10-28 14:52:55.549277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eca5e33adc1'
down_revision: Union[str, None] = 'c100e49e9a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Storage', sa.Column('key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Storage', 'key')
    # ### end Alembic commands ###
