"""Change User model

Revision ID: 8fd5c3266899
Revises: 6eca5e33adc1
Create Date: 2024-11-27 12:23:12.146436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd5c3266899'
down_revision: Union[str, None] = '6eca5e33adc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('User', 'google_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('google_access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('User', 'password')
    # ### end Alembic commands ###
