"""Add key in StorageModel

Revision ID: c100e49e9a9d
Revises: dd17b2bd100f
Create Date: 2024-10-28 14:52:11.462644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c100e49e9a9d'
down_revision: Union[str, None] = 'dd17b2bd100f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Storage', sa.Column('key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Storage', 'key')
    # ### end Alembic commands ###
