"""Change User model

Revision ID: c5a9d99461bc
Revises: 8fd5c3266899
Create Date: 2024-11-27 12:27:26.182510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a9d99461bc'
down_revision: Union[str, None] = '8fd5c3266899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
